# Generated by Django 2.2.10 on 2020-05-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='9818195512', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BC', 'Baby Care'), ('CP', 'Capsules'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
