# Generated by Django 2.2.10 on 2020-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200503_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('BTM', 'BIRTAMOD'), ('DMK', 'DAMAK'), ('BTB', 'BIRTABAZAR'), ('SNC', 'SANISCHARE')], default='BIRTAMOD', max_length=3),
            preserve_default=False,
        ),
    ]
